/*
	Configuration options used by platform specific code.

	This file is automatically generated by the build system,
	which tries to know what options are valid in what
	combinations. Avoid changing this file manually unless
	you know what you're doing.
*/

#include <windows.h>
#include <time.h>
#include <shlobj.h>
#include <tchar.h>


#define RomFileName "MacII.ROM"
#define kCheckSumRom_Size 0x00040000
#define kRomCheckSum1 0x9779D2C4
#define kRomCheckSum2 0x97221136
#define CheckRomCheckSum 0
#define RomStartCheckSum 1
#define dbglog_buflnsz 18
#define EnableDragDrop 1
#define SaveDialogEnable 1
#define EnableAltKeysMode 0
#define MKC_formac_Control MKC_Control
#define MKC_formac_Command MKC_Command
#define MKC_formac_Option MKC_Option
#define MKC_formac_Shift MKC_Shift
#define MKC_formac_CapsLock MKC_CapsLock
#define MKC_formac_Escape MKC_Escape
#define MKC_formac_BackSlash MKC_BackSlash
#define MKC_formac_Slash MKC_Slash
#define MKC_formac_Grave MKC_Grave
#define MKC_formac_Enter MKC_Enter
#define MKC_formac_PageUp MKC_PageUp
#define MKC_formac_PageDown MKC_PageDown
#define MKC_formac_Home MKC_Home
#define MKC_formac_End MKC_End
#define MKC_formac_Help MKC_Help
#define MKC_formac_ForwardDel MKC_ForwardDel
#define MKC_formac_F1 MKC_CM
#define MKC_formac_F2 MKC_Command
#define MKC_formac_F3 MKC_F3
#define MKC_formac_F4 MKC_F4
#define MKC_formac_F5 MKC_F5
#define MKC_formac_RControl MKC_CM
#define MKC_formac_RCommand MKC_Command
#define MKC_formac_ROption MKC_Option
#define MKC_formac_RShift MKC_Shift
#define kControlModeKey "F1"
#define kUnMappedKey "F1"
#define MKC_UnMappedKey  MKC_F1
#define VarFullScreen 1
#define WantInitFullScreen 0
#define MayFullScreen 1
#define MayNotFullScreen 1
#define WantInitMagnify 0
#define EnableMagnify 1
#define MyWindowScale 3
#define GrabKeysFullScreen 0
#define WantInitRunInBackground 0
#define WantInitNotAutoSlow 1
#define WantInitSpeedValue 5
#define WantEnblCtrlInt 1
#define WantEnblCtrlRst 1
#define WantEnblCtrlKtg 0
#define NeedRequestInsertDisk 1
#define NeedRequestIthDisk 1
#define NeedDoMoreCommandsMsg 1
#define NeedDoAboutMsg 1
#define UseControlKeys 1
#define UseActvCode 0
#define EnableDemoMsg 0

/* version and other info to display to user */

#define NeedIntlChars 0
#define ItnlKyBdFix 1
#define kStrAppName "Mini vMac"
#define kCustomWindowTitle "Mini vMac Plus"
#define kAppVariationStr "minivmac-plus-0.1"
#define kStrCopyrightYear "2018"
#define kMaintainerName "unknown"
#define kStrHomePage "https://www.gryphel.com/c/minivmac/"

#define kBldOpts "-br 36 -t wx86 -d d -m II -hres 640 -vres 400 -fullscreen 0 -mf 3 -magnify 0 -gkf 0 -drives 4 -sss 3 -sony-tag 1 -sony-sum 1 -iid 1 -km Control Control -km F1 CM -km RControl CM -speed 5 -ta 2 -cbt 3 -dct 5 -mnb 1 -kyt 3 -kyr 1 -eck 0 -chr 0 -dis 0 -log 0 -abr 1"
